OUT_OF_RANGE_THRESHOLD_FACTOR = 5
MAX_DATA_POINTS = 500
EXPECTED_BASE = 50
EXPECTED_VARIANCE = 20
DROP_PACKET_CHANCE = 30   # TYPE PERCENTAGE
PUBLISHING_TIME = 0.5


# CONNECTION SETTINGS
MQTT_BROKER_URL = "localhost"
MQTT_BROKER_PORT = "1883"
MQTT_TOPIC = "iot/data"

